
#FGD1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run2a_air_p6T_rdp_fhc.list 22 data_run2a_air_p6T_rdp_fhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run2a_water_p6T_rdp_fhc.list 51 data_run2a_water_p6T_rdp_fhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run3b_air_p6T_rdp_fhc.list 15 data_run3b_air_p6T_rdp_fhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run3c_air_p6T_rdp_fhc.list 33 data_run3c_air_p6T_rdp_fhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run4a_air_p6T_rdp_fhc.list 31 data_run4a_air_p6T_rdp_fhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run4a_water_p6T_rdp_fhc.list 35 data_run4a_water_p6T_rdp_fhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run8a_air_p6V_rdp_fhc.list 47 data_run8a_air_p6V_rdp_fhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run8a_water_p6V_rdp_fhc.list 31 data_run8a_water_p6V_rdp_fhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run5c_water_p6T_rdp_rhc.list 10 data_run5c_water_p6T_rdp_rhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run6b_air_p6T_rdp_rhc.list 24 data_run6b_air_p6T_rdp_rhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run6c_air_p6T_rdp_rhc.list 7 data_run6c_air_p6T_rdp_rhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run6d_air_p6T_rdp_rhc.list 10 data_run6d_air_p6T_rdp_rhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run6e_air_p6T_rdp_rhc.list 12 data_run6e_air_p6T_rdp_rhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run7b_water_p6T_rdp_rhc.list 32 data_run7b_water_p6T_rdp_rhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run9b_water_p6T_rdp_rhc.list 7 data_run9b_water_p6T_rdp_rhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run9c_water_p6T_rdp_rhc.list 8 data_run9c_water_p6T_rdp_rhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat data_run9d_water_p6T_rdp_rhc.list 13 data_run9d_water_p6T_rdp_rhc_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat neut_fhc_run2air_p6T.list 60 neut_fhc_run2air_p6T_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat neut_fhc_run2water_p6T.list 43 neut_fhc_run2water_p6T_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat neut_fhc_run3air_p6T.list 110 neut_fhc_run3air_p6T_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat neut_fhc_run4air_p6T.list 129 neut_fhc_run4air_p6T_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat neut_fhc_run4water_p6T.list 129 neut_fhc_run4water_p6T_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat neut_fhc_run8air_p6T.list 159 neut_fhc_run8air_p6T_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat neut_fhc_run8water_p6T.list 97 neut_fhc_run8water_p6T_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat neut_rhc_run5water_p6T.list 80 neut_rhc_run5water_p6T_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat neut_rhc_run6air_p6T.list 125 neut_rhc_run6air_p6T_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat neut_rhc_run7water_p6T.list 119 neut_rhc_run7water_p6T_fgd1
sh run_with_split_on_farm.sh myLDMAnalysis.FGD1.parameters.dat neut_rhc_run9water_p6T.list 94 neut_rhc_run9water_p6T_fgd1


#FGD2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run2a_air_p6T_rdp_fhc.list 22 data_run2a_air_p6T_rdp_fhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run2a_water_p6T_rdp_fhc.list 51 data_run2a_water_p6T_rdp_fhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run3b_air_p6T_rdp_fhc.list 15 data_run3b_air_p6T_rdp_fhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run3c_air_p6T_rdp_fhc.list 33 data_run3c_air_p6T_rdp_fhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run4a_air_p6T_rdp_fhc.list 31 data_run4a_air_p6T_rdp_fhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run4a_water_p6T_rdp_fhc.list 35 data_run4a_water_p6T_rdp_fhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run8a_air_p6V_rdp_fhc.list 47 data_run8a_air_p6V_rdp_fhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run8a_water_p6V_rdp_fhc.list 31 data_run8a_water_p6V_rdp_fhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run5c_water_p6T_rdp_rhc.list 10 data_run5c_water_p6T_rdp_rhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run6b_air_p6T_rdp_rhc.list 24 data_run6b_air_p6T_rdp_rhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run6c_air_p6T_rdp_rhc.list 7 data_run6c_air_p6T_rdp_rhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run6d_air_p6T_rdp_rhc.list 10 data_run6d_air_p6T_rdp_rhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run6e_air_p6T_rdp_rhc.list 12 data_run6e_air_p6T_rdp_rhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run7b_water_p6T_rdp_rhc.list 32 data_run7b_water_p6T_rdp_rhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run9b_water_p6T_rdp_rhc.list 7 data_run9b_water_p6T_rdp_rhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run9c_water_p6T_rdp_rhc.list 8 data_run9c_water_p6T_rdp_rhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat data_run9d_water_p6T_rdp_rhc.list 13 data_run9d_water_p6T_rdp_rhc_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat neut_fhc_run2air_p6T.list 60 neut_fhc_run2air_p6T_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat neut_fhc_run2water_p6T.list 43 neut_fhc_run2water_p6T_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat neut_fhc_run3air_p6T.list 110 neut_fhc_run3air_p6T_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat neut_fhc_run4air_p6T.list 129 neut_fhc_run4air_p6T_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat neut_fhc_run4water_p6T.list 129 neut_fhc_run4water_p6T_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat neut_fhc_run8air_p6T.list 159 neut_fhc_run8air_p6T_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat neut_fhc_run8water_p6T.list 97 neut_fhc_run8water_p6T_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat neut_rhc_run5water_p6T.list 80 neut_rhc_run5water_p6T_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat neut_rhc_run6air_p6T.list 125 neut_rhc_run6air_p6T_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat neut_rhc_run7water_p6T.list 119 neut_rhc_run7water_p6T_fgd2
sh run_with_split_on_farm.sh myLDMAnalysis.FGD2.parameters.dat neut_rhc_run9water_p6T.list 94 neut_rhc_run9water_p6T_fgd2






